version: '3'
services:

  aws_ssm:
    image: cmattoon/aws-ssm:latest
    build:
      context: .
    volumes:
      - /path/to/.kube:/.kube
    ports:
      - "9999:9999"
    environment:
      KUBE_CONFIG: "/.kube/config"
      AWS_REGION: ""
      AWS_ACCESS_KEY: ""
      AWS_SECRET_KEY: ""
      MASTER_URL: ""
      
        
