# AWS Region
aws:
  region: ""
  access_key: ""
  secret_key: ""
# The contents of your ~/.kube/config, base64-encoded
kubeconfig64: ""
# URL to Kubernetes master API
master_url: ""
# Healthcheck stuff
metrics_port: 9999
# Number of replicas
replicas: 1
# Docker image for aws-ssm
image:
  name: cmattoon/aws-ssm
  tag: v0.1.0
# Pod Resources
resources: {}
  
rbac:
  enabled: true
  
